// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-gWOlR_zUUsVDbGFVi8s8paaJxyez78',
    appId: '1:762047865975:web:9dc5f97e1126a4f32f5272',
    messagingSenderId: '762047865975',
    projectId: 'user-management-system-e0b64',
    authDomain: 'user-management-system-e0b64.firebaseapp.com',
    storageBucket: 'user-management-system-e0b64.appspot.com',
    measurementId: 'G-NFY4J5FBDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZRdONWYhXzpikTCustBDFqcrWd1CUQk',
    appId: '1:762047865975:android:0744361933cf6e732f5272',
    messagingSenderId: '762047865975',
    projectId: 'user-management-system-e0b64',
    storageBucket: 'user-management-system-e0b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD--d1_zMAUGjTUbvBo6eaax99OAoBTPis',
    appId: '1:762047865975:ios:b7a28f9cc655bf0e2f5272',
    messagingSenderId: '762047865975',
    projectId: 'user-management-system-e0b64',
    storageBucket: 'user-management-system-e0b64.appspot.com',
    iosBundleId: 'com.example.userManagementSystem',
  );
}
